// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfwcsbchajyzgstsbson.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmd2NzYmNoYWp5emdzdHNic29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDMxODUsImV4cCI6MjA2NjcxOTE4NX0.4isg7M1Q8ZQxn6VmRddms4QADDKi2sC9XYDmxIZapu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);